### ISSUE TITLE
CSS Modules

### ISSUE THREAD

**Issue by HairyRabbit** [blisss/notes#3]
# CSS Modules

没错，是css模块。

从JS趋于模块化发展的尿性来看，CSS也会朝这个方向看齐。
## 首先，问题是什么？
1. 从组件的角度思考，组件的样式也属于组件的组成部分。
2. 所有的CSS属于全局。
3. 与JS的互操作。

首先，从**bootstrap**一类的css库可以看的出主要是组件的样式，比如最有诚意的按钮样式，`btn btn-primary`。

其次全局问题确实是个棘手问题，这样经常会引来各式各样的覆盖问题，所以开发者必须遵循一定规范。

BEM是解决这类问题的一个方案。`Block__Element--modifier`，遵循这套命名规范，基本可以保证类名不重复。

第三点也很长用，考虑下面的`jQuery`代码：

``` js
$el.addClass("active");
```

然而问题很明显，`"active"`来自于样式表，来源于一定的约定或配置。

如果`"active"`改成了`"animate-in"`呢？所有引用到的字符串都需要改变一次。

那么，如何解决？
## 休息一下，看个简单示例

不如我们先看下面的代码：

``` css
.btn {
    background-color: red;
}

.btn--active {
    background-color: green;
}

/* 将样式导出，就像js那样 */
:export {
    active: .btn--active;
}
```

``` js
import $ from "jquery";
import btnStyle from "./button.css";

// btnStyle = { active: ".btn--active" }
$btn.addClass(btnStyle.active);
```

如果这么做可行，那恼人的样式改变问题就解决了。

然而，确实可行。我们需要[Webpack](http://webpack.github.io/docs/tutorials/getting-started/)。
## Webpack 什么鬼？

如果你和我一样，从`Grunt`，`Gulp`一路走来。那么这个时代属于`Webpack`。

同为构建系统，`webpack`把模块化的思想发挥到了极致，所有的一切，都是模块，图片、样式、文档，当然，还有JS。使用得当，就可以把依赖问题降到最低。

`Grunt`配置各种插件，`Gulp`管理文件流，`Webpack`使用**loader**处理依赖。

当然，只是简单聊聊，毕竟不是主角。

接下来就可以用`Webpack`来解决css依赖问题。在开始之前还是再聊聊[css-modules](https://github.com/css-modules/css-modules)吧。
## 再来看看 css-modules

上面的例子中看到了`:export`伪类，你可能会想象应该还有`:import`。

答案是肯定的，就算是css，他也可能依赖其他css样式。`less`，`sass`已经做到了这一点。

不过，这里所说的`import`和上面的`import`不一样。这里的`import`有点像es6中的`import`，他要求引入的文件要`export`类似`JS`中对象的东西。

``` css
/* test.css */
.test__module {
    color: red;
}

:export {
    test: test__module;
}

/* main.css */
:import(./test.css) {
    testModule: test
}
```

你一定看明白`import`了，然后我们聊聊`:local`和`:global`。

为了避免样式在全局重复后覆盖，最绅士的办法就是把类名换成全局唯一。简单一些的，用**base64**编码一下类名，然后有诚意的`export`就可以了。这样我们打开样式表会开心的看到一大堆base64编码的类名，然后在标签中也会发现他们。这就是`:local`的作用。

当然，有时候还是不得不使用全局样式，那么就使用`:global`，他不会被编码。

``` css
/* 手撸的样式 */
:local(.btn) { background: red; }

/* 编码后的样式 */
._23_aKvs-b8bW2Vg3fwHozO { background: red; }

/* 全局样式 */
:global(.btn-s) { background: blue; }

/* 并不会编码 */
.btn-s { background: blue; }

/* 导出 */
:export {
    btn: "_23_aKvs-b8bW2Vg3fwHozO",
    btn-s: "btn-s"
}
```

``` js
import { btn } from "./button.css";

$el.toggleClass(btn);
```

那么还有一个问题，在其他语言中，import除了申明在页面顶部外，也可以在内联起来使用。

``` js
require("unit").format("%s is bar", "foo");
//=> "foo is bar"
```

css也可以，不过要使用`composes`。

``` css
.test {
    composes: btn from "./button.css";
}
```

基本就是这些，接下来简单配置一下工具。
## 准备就绪

正如之前提到的，首先要安装对应的`loader`

``` sh
# npm install style-loader css-loader --save
```

修改配置文件`webpack.config.js`：

``` js
module: {
    loaders: [
        { test: /\.css$/, loader: "style!css" }
    ]
}
```

这样就可以简单使用了，当然，有一些配置项要了解一下。

还记得前边提到的`:local`么？再来巩固一下。

使用`:local`关键字可以导出成对象使用。

``` css
/* main.css */
:local(.test) {
    color: green;
}
```

``` js
import Main from "./main.css";

console.log(Main);

//=> { test: "23aKvs-b8bW2Vg3fwHozO" }
```

就如所见的那样，类名会被编码成**base64**格式。

可以指定导出格式，比如：

``` url
!css?localIdentName=[path]-[name]__[local]--[hash:base64:5]
```

会导出成：

``` css
._-main__test1--2fOof {
    color: green;
}
```

如果我们想让所有的类名自动编码，需要申明`modules`。

``` url
!css?modules
```

生成SourceMaps和压缩文件的配置比较简单

``` url
!css?sourceMap
```

``` url
// 启用
!css?minimize

// 不启用
!css?-minimize
```

然后是我的`loader`。

``` url
css?sourceMap&modules&importLoaders=1&localIdentName=[path]-[name]__[local]--[hash:base64:5]&-minimize
```
## Summary

。。。

**Comment by yuffiy** [comment]
# CSS Modules

没错，是css模块。

从JS趋于模块化发展的尿性来看，CSS也会朝这个方向看齐。

## 首先，问题是什么？

1. 从组件的角度思考，组件的样式也属于组件的组成部分。
2. 所有的CSS属于全局。
3. 与JS的互操作。

首先，从__bootstrap__一类的css库可以看的出主要是组件的样式，比如最有诚意的按钮样式，`btn btn-primary`。

其次全局问题确实是个棘手问题，这样经常会引来各式各样的覆盖问题，所以开发者必须遵循一定规范。

BEM是解决这类问题的一个方案。`Block__Element--modifier`，遵循这套命名规范，基本可以保证类名不重复。

第三点也很长用，考虑下面的`jQuery`代码：

```js
$el.addClass("active");
```

然而问题很明显，`"active"`来自于样式表，来源于一定的约定或配置。

如果`"active"`改成了`"animate-in"`呢？所有引用到的字符串都需要改变一次。

那么，如何解决？

## 休息一下，看个简单示例

不如我们先看下面的代码：

```css
.btn {
	background-color: red;
}
	
.btn--active {
	background-color: green;
}

/* 将样式导出，就像js那样 */
:export {
	active: .btn--active;
}
```

```js
import $ from "jquery";
import btnStyle from "./button.css";

// btnStyle = { active: ".btn--active" }
$btn.addClass(btnStyle.active);
```

如果这么做可行，那恼人的样式改变问题就解决了。

然而，确实可行。我们需要[Webpack](http://webpack.github.io/docs/tutorials/getting-started/)。

## Webpack 什么鬼？

如果你和我一样，从`Grunt`，`Gulp`一路走来。那么这个时代属于`Webpack`。

同为构建系统，`webpack`把模块化的思想发挥到了极致，所有的一切，都是模块，图片、样式、文档，当然，还有JS。使用得当，就可以把依赖问题降到最低。

`Grunt`配置各种插件，`Gulp`管理文件流，`Webpack`使用**loader**处理依赖。

当然，只是简单聊聊，毕竟不是主角。

接下来就可以用`Webpack`来解决css依赖问题。在开始之前还是再聊聊[css-modules](https://github.com/css-modules/css-modules)吧。

## 再来看看 css-modules

上面的例子中看到了`:export`伪类，你可能会想象应该还有`:import`。

答案是肯定的，就算是css，他也可能依赖其他css样式。`less`，`sass`已经做到了这一点。

不过，这里所说的`import`和上面的`import`不一样。这里的`import`有点像es6中的`import`，他要求引入的文件要`export`类似`JS`中对象的东西。

```css
/* test.css */
.test__module {
	color: red;
}
	
:export {
	test: test__module;
}

/* main.css */
:import(./test.css) {
	testModule: test
}
```

你一定看明白`import`了，然后我们聊聊`:local`和`:global`。

为了避免样式在全局重复后覆盖，最绅士的办法就是把类名换成全局唯一。简单一些的，用__base64__编码一下类名，然后有诚意的`export`就可以了。这样我们打开样式表会开心的看到一大堆base64编码的类名，然后在标签中也会发现他们。这就是`:local`的作用。

当然，有时候还是不得不使用全局样式，那么就使用`:global`，他不会被编码。

```css
/* 手撸的样式 */
:local(.btn) { background: red; }

/* 编码后的样式 */
._23_aKvs-b8bW2Vg3fwHozO { background: red; }

/* 全局样式 */
:global(.btn-s) { background: blue; }

/* 并不会编码 */
.btn-s { background: blue; }

/* 导出 */
:export {
	btn: "_23_aKvs-b8bW2Vg3fwHozO",
	btn-s: "btn-s"
}
```

```js
import { btn } from "./button.css";

$el.toggleClass(btn);
```

那么还有一个问题，在其他语言中，import除了申明在页面顶部外，也可以在内联起来使用。

```js
require("unit").format("%s is bar", "foo");
//=> "foo is bar"
```

css也可以，不过要使用`composes`。

```css
.test {
	composes: btn from "./button.css";
}
```

基本就是这些，接下来简单配置一下工具。

## 准备就绪

正如之前提到的，首先要安装对应的`loader`

```sh
# npm install style-loader css-loader --save
```

修改配置文件`webpack.config.js`：

```js
module: {
	loaders: [
		{ test: /\.css$/, loader: "style!css" }
	]
}
```

这样就可以简单使用了，当然，有一些配置项要了解一下。

还记得前边提到的`:local`么？再来巩固一下。

使用`:local`关键字可以导出成对象使用。

```css
/* main.css */
:local(.test) {
	color: green;
}
```

```js
import Main from "./main.css";

console.log(Main);

//=> { test: "23aKvs-b8bW2Vg3fwHozO" }
```

就如所见的那样，类名会被编码成**base64**格式。

可以指定导出格式，比如：

```url
!css?localIdentName=[path]-[name]__[local]--[hash:base64:5]
```

会导出成：

```css
._-main__test1--2fOof {
    color: green;
}
```

如果我们想让所有的类名自动编码，需要申明`modules`。

```url
!css?modules
```

生成SourceMaps和压缩文件的配置比较简单

```url
!css?sourceMap
```

```url
// 启用
!css?minimize

// 不启用
!css?-minimize
```

然后是我的`loader`。

```url
css?sourceMap&modules&importLoaders=1&localIdentName=[path]-[name]__[local]--[hash:base64:5]&-minimize
```

## Summary

。。。
